=== JohnYangSam/QuizSite/src/quizsite/util/quiz-xml/quiz.dtd
<!ELEMENT quiz (title, category?, description, question+)>
<!ATTLIST quiz
	random		(true | false)		"true"
	one-page	(true | false)		"true"
	immediate-correction	(true | false)	"false"
	practice-mode			(true | false)	"true"
	>

<!ELEMENT title (#PCDATA)>

<!ELEMENT category (#PCDATA)>

<!ELEMENT description (#PCDATA)>	

<!ELEMENT question (((query | image-location | blank-query), (answer | answer-list))
						| (query, option+))>
<!ATTLIST question 
	type (question-response | fill-in-blank | multiple-choice | picture-response)  #REQUIRED
	>

<!ELEMENT query (#PCDATA)>
<!ELEMENT blank-query (pre, blank, post)>
<!ELEMENT pre (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT blank EMPTY>

<!ELEMENT image-location (#PCDATA)>

<!ELEMENT option (#PCDATA)>
<!ATTLIST option answer (answer) #IMPLIED>

<!ELEMENT answer (#PCDATA)>
<!ATTLIST answer preferred (preferred) #IMPLIED>

<!ELEMENT answer-list (answer)+>

=== JohnYangSam/QuizSite/src/quizsite/util/quiz-xml/bunny.xml
<?xml version="1.0"?>
<!DOCTYPE note SYSTEM "quiz.dtd">
<quiz random="true" one-page="false" practice-mode="true">
<title>Bunny Quiz</title>
<category>Animals</category>
<description>An homag'e to the departed, legendary Bunny World project.</description>

<question type="question-response">
  <query>What is the Biological Family for Bunnies?</query>
  <answer>Leporidae</answer>
</question>

<question type="fill-in-blank">
  <blank-query><pre>The book</pre><blank /><post>Down, about a bunch of rabbits, won the 1972 Carnegie Medal</post></blank-query>
  <answer>Watership</answer>
</question>

<question type="multiple-choice">
  <query>Which of the following statements is false</query>
  <option>Aztec mythology includes a rabbit pantheon.</option>
  <option>In Japanese folklore, rabbits live on the moon.</option>
  <option answer="answer">In Stanford tradition, rubbing the nose of a rabbit guarantees an A on the CS108 class project</option>
</question>

<question type="picture-response">
  <image-location>http://upload.wikimedia.org/wikipedia/en/b/b9/Bugs_Bunny_Pose.PNG</image-location>
  <answer-list>
    <answer preferred="preferred">Bugs Bunny</answer>
	<answer>Bugs</answer>
  </answer-list>
</question>

</quiz>
